name: telegram message
on: 
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, closed]

jobs:
  notify:
    name: Notify Telegram
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram message on pull request
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            **${{ github.actor }} created a pull request in branch `${{ github.ref_name }}`:**
            **Pull request**: [${{ github.event.pull_request.title }}](${{ github.event.pull_request.html_url }})

            **Repository**: ${{ github.repository }}
            [**View Pull Request**](${{ github.event.pull_request.html_url }})
          parse_mode: Markdown

      - name: Send Telegram message on merge to any branch
        if: github.event_name == 'push'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            **Branch `${{ github.ref_name }}` was successfully pushed by ${{ github.actor }}!**
            **Repository**: ${{ github.repository }}
            **See latest commit**: ${{ github.event.head_commit.url }}
          parse_mode: Markdown
