name: telegram message
on: 
  push: 
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push or pull request
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ${{ github.actor }} created a pull request:
            Pull request title: ${{ github.event.pull_request.title }}
            
            Repository: ${{ github.repository }}
            See changes: ${{ github.event.pull_request.html_url }}
