version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'minute'
    target-branch: 'develop'
    open-pull-requests-limit: 10
    commit-message:
      prefix: 'deps'
      include:
        prefix-development-only: true
