version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
      minutes: 1
    target-branch: "develop"
    groups:
      all-actions:
        patterns: [ "*" ]

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
      minutes: 1
    target-branch: "develop"
    groups:
      scss:
        patterns:
          - "node-sass"
          - "sass"
